# eye-comfort-se-midgard — morning (OKLCH SoT → hex)
accent = "#436354"
cursor = "#855823"
foreground = "#2B2723"
background = "#F9F1E4"
selection_foreground = "#2B2723"
selection_background = "#E5DDD0"

color0 = "#E5DDD0"
color1 = "#A1453C"
color2 = "#436354"
color3 = "#855823"
color4 = "#435D60"
color5 = "#84644C"
color6 = "#406E60"
color7 = "#625C57"
color8 = "#726A61"
color9 = "#B45248"
color10 = "#557864"
color11 = "#8C5500"
color12 = "#536F72"
color13 = "#967157"
color14 = "#4B7D6E"
color15 = "#2B2723"
