# eye-comfort-tn-neythal — afternoon (OKLCH SoT → hex)
accent = "#3F6052"
cursor = "#855B1B"
foreground = "#2C2622"
background = "#FBEEE1"
selection_foreground = "#2C2622"
selection_background = "#E7DACD"

color0 = "#E7DACD"
color1 = "#A1453C"
color2 = "#3F6052"
color3 = "#855B1B"
color4 = "#435C5C"
color5 = "#89644C"
color6 = "#406D64"
color7 = "#625B54"
color8 = "#72685E"
color9 = "#B45248"
color10 = "#537866"
color11 = "#905500"
color12 = "#546D6D"
color13 = "#9A7157"
color14 = "#4A7D73"
color15 = "#2C2622"
