background = #FBEEE1
foreground = #2C2622
cursor-color = #855B1B
selection-background = #E7DACD
selection-foreground = #2C2622

palette = 0=#E7DACD
palette = 1=#A1453C
palette = 2=#3F6052
palette = 3=#855B1B
palette = 4=#435C5C
palette = 5=#89644C
palette = 6=#406D64
palette = 7=#625B54
palette = 8=#72685E
palette = 9=#B45248
palette = 10=#537866
palette = 11=#905500
palette = 12=#546D6D
palette = 13=#9A7157
palette = 14=#4A7D73
palette = 15=#2C2622
