background = #181512
foreground = #E6DFD3
cursor-color = #CEA36D
selection-background = #2A2520
selection-foreground = #E6DFD3

palette = 0=#2A2520
palette = 1=#C47064
palette = 2=#7E9A8A
palette = 3=#CEA36D
palette = 4=#708C8E
palette = 5=#AB8970
palette = 6=#7EA197
palette = 7=#E7E0D4
palette = 8=#8A8278
palette = 9=#D67B6F
palette = 10=#88A793
palette = 11=#D4A05A
palette = 12=#7F9899
palette = 13=#BC957A
palette = 14=#82ACA0
palette = 15=#EAE4D9
