background = #1A1612
foreground = #E6DFD3
cursor-color = #CCA46C
selection-background = #2C2621
selection-foreground = #E6DFD3

palette = 0=#2C2621
palette = 1=#C47064
palette = 2=#7F9A8A
palette = 3=#CCA46C
palette = 4=#708C8E
palette = 5=#AC8972
palette = 6=#80A194
palette = 7=#E7E0D4
palette = 8=#8A8278
palette = 9=#D67B6F
palette = 10=#89A792
palette = 11=#D4A05A
palette = 12=#7F9899
palette = 13=#BC957B
palette = 14=#84AC9D
palette = 15=#EAE4D9
