# eye-comfort-dawn — circadian dawn (OKLCH SoT → hex)
accent = "#476655"
cursor = "#332C28"
foreground = "#332C28"
background = "#F8E7DE"
selection_foreground = "#332C28"
selection_background = "#E7D5CB"

color0 = "#E7D5CB"
color1 = "#A34A40"
color2 = "#476655"
color3 = "#895F2E"
color4 = "#49626E"
color5 = "#8B6953"
color6 = "#446D62"
color7 = "#5B544F"
color8 = "#72665F"
color9 = "#B2544A"
color10 = "#577862"
color11 = "#976213"
color12 = "#516E7C"
color13 = "#977158"
color14 = "#517F73"
color15 = "#332C28"
