# eye-comfort-tn-marutham — dawn (OKLCH SoT → hex)
accent = "#476656"
cursor = "#895F2E"
foreground = "#332C28"
background = "#F9E7DA"
selection_foreground = "#332C28"
selection_background = "#E5D3C7"

color0 = "#E5D3C7"
color1 = "#A34A40"
color2 = "#476656"
color3 = "#895F2E"
color4 = "#4B6264"
color5 = "#8B6953"
color6 = "#456D61"
color7 = "#5B544F"
color8 = "#72665F"
color9 = "#B2544A"
color10 = "#557864"
color11 = "#976213"
color12 = "#536F72"
color13 = "#977158"
color14 = "#527F72"
color15 = "#332C28"
