# eye-comfort-se-jotunheim — dusk (OKLCH SoT → hex)
accent = "#84A18D"
cursor = "#DBA76C"
foreground = "#E8DED0"
background = "#302821"
selection_foreground = "#E8DED0"
selection_background = "#44392F"

color0 = "#44392F"
color1 = "#D17469"
color2 = "#84A18D"
color3 = "#DBA76C"
color4 = "#799192"
color5 = "#B89077"
color6 = "#83A899"
color7 = "#E8DED0"
color8 = "#91867A"
color9 = "#E07F73"
color10 = "#8FAE96"
color11 = "#DDA55C"
color12 = "#839E9F"
color13 = "#C69A7F"
color14 = "#8AB2A2"
color15 = "#E9E2D6"
