background = #302821
foreground = #E8DED0
cursor-color = #DBA76C
selection-background = #44392F
selection-foreground = #E8DED0

palette = 0=#44392F
palette = 1=#D17469
palette = 2=#84A18D
palette = 3=#DBA76C
palette = 4=#799192
palette = 5=#B89077
palette = 6=#83A899
palette = 7=#E8DED0
palette = 8=#91867A
palette = 9=#E07F73
palette = 10=#8FAE96
palette = 11=#DDA55C
palette = 12=#839E9F
palette = 13=#C69A7F
palette = 14=#8AB2A2
palette = 15=#E9E2D6
