background = #FCF1E5
foreground = #2A2622
cursor-color = #8C5F33
selection-background = #E8DDD1
selection-foreground = #2A2622

palette = 0=#E8DDD1
palette = 1=#B54A40
palette = 2=#506A56
palette = 3=#8C5F33
palette = 4=#405B5B
palette = 5=#8E6952
palette = 6=#446C59
palette = 7=#605A54
palette = 8=#6E665C
palette = 9=#B25046
palette = 10=#5A755D
palette = 11=#8B6020
palette = 12=#516C6C
palette = 13=#966F59
palette = 14=#4E7C66
palette = 15=#2A2622
