#!/bin/bash
# Omarchy theme-set.d hook: keep git-delta (+ optional bat) in eye-comfort mode.
# Installed to ~/.config/omarchy/hooks/theme-set.d/ by eye-comfort install.sh
#
# Why: delta defaults (Dracula + dark minus/plus #3f0001/#002800) fight cream
# day packages and look muddy on warm paper. Features live in
# ~/.config/git/verification (or shell git.ex.config); this hook only flips
# delta.features = eye-comfort-light|dark from light.mode.

THEME_NAME="${1:-}"
LIGHT_MODE="${HOME}/.config/omarchy/current/theme/light.mode"
GIT_DELTA_CFG="${XDG_CONFIG_HOME:-$HOME/.config}/git/verification"
STATE_ENV="${XDG_CONFIG_HOME:-$HOME/.config}/eye-comfort/delta.env"

mode="eye-comfort-dark"
bat_theme="ansi"
if [[ -f "$LIGHT_MODE" ]]; then
  mode="eye-comfort-light"
  bat_theme="ansi"
fi

# Prefer the verification include (migrate target). Fall back to global.
if [[ -f "$GIT_DELTA_CFG" ]]; then
  git config --file "$GIT_DELTA_CFG" delta.features "$mode" 2>/dev/null || true
else
  git config --global delta.features "$mode" 2>/dev/null || true
fi

# Session-friendly env snippet (shells that source eye-comfort after theme swap)
mkdir -p "$(dirname "$STATE_ENV")" 2>/dev/null || true
cat >"$STATE_ENV" <<EOF
# Generated by eye-comfort 91-delta-bat.sh — do not edit
# theme=${THEME_NAME:-unknown} mode=${mode}
export DELTA_FEATURES="${mode}"
# ansi follows Ghostty 16-color SoT (eye-comfort roles); override if desired
export BAT_THEME="${bat_theme}"
EOF

if [[ -n "${EC_THEME_HOOK_DEBUG:-}" ]]; then
  echo "eye-comfort theme-set.d: delta.features=${mode} theme=${THEME_NAME}" >&2
fi
