# eye-comfort-dusk — dusk (OKLCH SoT → hex)
accent = "#81A191"
cursor = "#D5AB68"
foreground = "#E8DED0"
background = "#322821"
selection_foreground = "#E8DED0"
selection_background = "#44382F"

color0 = "#44382F"
color1 = "#D17469"
color2 = "#81A191"
color3 = "#D5AB68"
color4 = "#799194"
color5 = "#B59274"
color6 = "#82A89B"
color7 = "#E8DED0"
color8 = "#91867A"
color9 = "#E07F73"
color10 = "#8DAE98"
color11 = "#DDA55C"
color12 = "#839EA1"
color13 = "#C49B7C"
color14 = "#88B2A4"
color15 = "#E9E2D6"
