# eye-comfort-se-vanaheim — dawn (OKLCH SoT → hex)
accent = "#496652"
cursor = "#85622B"
foreground = "#332C28"
background = "#F7E7D9"
selection_foreground = "#332C28"
selection_background = "#E3D3C6"

color0 = "#E3D3C6"
color1 = "#A34A40"
color2 = "#496652"
color3 = "#85622B"
color4 = "#4B6262"
color5 = "#846D4D"
color6 = "#456D60"
color7 = "#5B544F"
color8 = "#72665F"
color9 = "#B2544A"
color10 = "#587860"
color11 = "#976213"
color12 = "#536F6F"
color13 = "#8F7651"
color14 = "#537F70"
color15 = "#332C28"
