# eye-comfort-tn-mullai — dusk (OKLCH SoT → hex)
accent = "#85A08D"
cursor = "#D0AE67"
foreground = "#E8DED0"
background = "#312921"
selection_foreground = "#E8DED0"
selection_background = "#453A30"

color0 = "#453A30"
color1 = "#D17469"
color2 = "#85A08D"
color3 = "#D0AE67"
color4 = "#79928F"
color5 = "#AB976F"
color6 = "#83A899"
color7 = "#E8DED0"
color8 = "#91867A"
color9 = "#E07F73"
color10 = "#8FAE95"
color11 = "#DDA55C"
color12 = "#849F9C"
color13 = "#B8A175"
color14 = "#8AB2A1"
color15 = "#E9E2D6"
