background = #F7F0E6
foreground = #2A2622
cursor-color = #89612F
selection-background = #E4DCD1
selection-foreground = #2A2622

palette = 0=#E4DCD1
palette = 1=#B54A40
palette = 2=#4C6B59
palette = 3=#89612F
palette = 4=#405B5D
palette = 5=#8C6A4F
palette = 6=#3E6C60
palette = 7=#605A54
palette = 8=#6E665C
palette = 9=#B25046
palette = 10=#567661
palette = 11=#8B6020
palette = 12=#516C6E
palette = 13=#947155
palette = 14=#487C6E
palette = 15=#2A2622
